### ISSUE TITLE
kafka-avro-console-producer Quick Start fails via Docker Quick start 

### ISSUE THREAD

**Issue by mokusachin** [confluentinc/libserdes#6]
Hi, i am  using kafka-avro-console-producer from confluent and i have the following error when ever i try to produce messages the command works fine but as soon as  i give my string value it throws me this following error. 

root@confluent:/#  /usr/bin/kafka-avro-console-producer   --broker-list localhost:29092 --topic barl   --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
ping
org.apache.kafka.common.errors.SerializationException: Error deserializing json ping to Avro of schema {"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}
Caused by: org.codehaus.jackson.JsonParseException: Unexpected character ('h' (code 104)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@60f00693; line: 1, column: 2]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
        at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:1198)
        at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:485)
        at org.apache.avro.io.JsonDecoder.configure(JsonDecoder.java:131)
        at org.apache.avro.io.JsonDecoder.<init>(JsonDecoder.java:73)
        at org.apache.avro.io.JsonDecoder.<init>(JsonDecoder.java:81)
        at org.apache.avro.io.DecoderFactory.jsonDecoder(DecoderFactory.java:268)
        at io.confluent.kafka.formatter.AvroMessageReader.jsonToAvro(AvroMessageReader.java:198)
        at io.confluent.kafka.formatter.AvroMessageReader.readMessage(AvroMessageReader.java:165)
        at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:59)
        at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)

**Comment by Labibme** [comment]
Hi, 
I have same error, and i tried many other msg but still same.
does anyone can help with that please?
thanks,

**Comment by edenhill** [comment]
The initial issue seems to have been using kafka-avro-console-producer, which is not part of libserdes.
Do you have the same issue with that tool? If so I suggest filing an issue [here](https://github.com/confluentinc/schema-registry/issues)
